# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/torospr/extract-files.sh - DO NOT EDIT

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES := \
    vendor/samsung/torospr/proprietary/libsecril-client.so:obj/lib/libsecril-client.so

# All the blobs necessary for torospr
PRODUCT_COPY_FILES += \
    vendor/samsung/torospr/proprietary/fRom:system/bin/fRom \
    vendor/samsung/torospr/proprietary/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/torospr/proprietary/libsyncml_core.so:system/lib/libsyncml_core.so \
    vendor/samsung/torospr/proprietary/libsyncml_port.so:system/lib/libsyncml_port.so \
    vendor/samsung/torospr/proprietary/pvrsrvinit:system/vendor/bin/pvrsrvinit \
    vendor/samsung/torospr/proprietary/sirfgps.conf:system/vendor/etc/sirfgps.conf \
    vendor/samsung/torospr/proprietary/smc_normal_world_android_cfg.ini:system/vendor/etc/smc_normal_world_android_cfg.ini \
    vendor/samsung/torospr/proprietary/bcm4330.hcd:system/vendor/firmware/bcm4330.hcd \
    vendor/samsung/torospr/proprietary/ducati-m3.bin:system/vendor/firmware/ducati-m3.bin \
    vendor/samsung/torospr/proprietary/libpn544_fw.so:system/vendor/firmware/libpn544_fw.so \
    vendor/samsung/torospr/proprietary/mms144_ts_rev31.fw:system/vendor/firmware/mms144_ts_rev31.fw \
    vendor/samsung/torospr/proprietary/mms144_ts_rev32.fw:system/vendor/firmware/mms144_ts_rev32.fw \
    vendor/samsung/torospr/proprietary/smc_pa_wvdrm.ift:system/vendor/firmware/smc_pa_wvdrm.ift \
    vendor/samsung/torospr/proprietary/libEGL_POWERVR_SGX540_120.so:system/vendor/lib/egl/libEGL_POWERVR_SGX540_120.so \
    vendor/samsung/torospr/proprietary/libGLESv1_CM_POWERVR_SGX540_120.so:system/vendor/lib/egl/libGLESv1_CM_POWERVR_SGX540_120.so \
    vendor/samsung/torospr/proprietary/libGLESv2_POWERVR_SGX540_120.so:system/vendor/lib/egl/libGLESv2_POWERVR_SGX540_120.so \
    vendor/samsung/torospr/proprietary/gps.omap4.so:system/vendor/lib/hw/gps.omap4.so \
    vendor/samsung/torospr/proprietary/gralloc.omap4.so:system/vendor/lib/hw/gralloc.omap4.so \
    vendor/samsung/torospr/proprietary/libglslcompiler.so:system/vendor/lib/libglslcompiler.so \
    vendor/samsung/torospr/proprietary/hwcomposer.omap4.so:system/vendor/lib/hw/hwcomposer.omap4.so \
    vendor/samsung/torospr/proprietary/libIMGegl.so:system/vendor/lib/libIMGegl.so \
    vendor/samsung/torospr/proprietary/libinvensense_mpl.so:system/vendor/lib/libinvensense_mpl.so \
    vendor/samsung/torospr/proprietary/libpvr2d.so:system/vendor/lib/libpvr2d.so \
    vendor/samsung/torospr/proprietary/libpvrANDROID_WSEGL.so:system/vendor/lib/libpvrANDROID_WSEGL.so \
    vendor/samsung/torospr/proprietary/libPVRScopeServices.so:system/vendor/lib/libPVRScopeServices.so \
    vendor/samsung/torospr/proprietary/libsec-ril_lte.so:system/vendor/lib/libsec-ril_lte.so \
    vendor/samsung/torospr/proprietary/libsrv_init.so:system/vendor/lib/libsrv_init.so \
    vendor/samsung/torospr/proprietary/libsrv_um.so:system/vendor/lib/libsrv_um.so \
    vendor/samsung/torospr/proprietary/libusc.so:system/vendor/lib/libusc.so \
    vendor/samsung/torospr/proprietary/libwvdrm_L1.so:system/vendor/lib/libwvdrm_L1.so \
    vendor/samsung/torospr/proprietary/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/samsung/torospr/proprietary/libWVStreamControlAPI_L1.so:system/vendor/lib/libWVStreamControlAPI_L1.so \
    vendor/samsung/torospr/proprietary/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
	vendor/samsung/torospr/proprietary/lib_gsd4t.so:system/lib/lib_gsd4t.so

# All the apks necessary for torospr
PRODUCT_PACKAGES += \
    HiddenMenu \
    BIP \
    SDM \
    SecPhone \
    SyncMLSvc

